[package]
name = "nitro"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
log = "0.4.21"
serde_json = "1.0"
base64 = "0.22.1"

[dependencies.uuid]
version = "1.8.0"
features = ["v4"]

